### ISSUE TITLE
bulk course export - ruby

### ISSUE THREAD

**Issue by goalearning** [unsupported/canvas#26]
Works well for us sometimes, other times it throws this error.  

ulk_course_export.rb:78:in `block (2 levels) in <main>': undefined method`[]' for nil:NilClass (NoMethodError)
    from /Users//.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1273:in `open'
    from bulk_course_export.rb:77:in`block in <main>'
    from /Users//.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1739:in `each'
    from /Users//.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1122:in`block in foreach'
    from /Users//.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1273:in `open'
    from /Users//.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/csv.rb:1121:in`foreach'
    from bulk_course_export.rb:57:in `<main>'

**Comment by goalearning** [comment]
Following up here, appears to occur with larger exports of classes.  Fiddled with the sleep time but didn't seem to matter.

**Comment by MattAttack07** [comment]
@goalearning when you say large exports, are you talking about quantity or size of the package. Can you give some examples of numbers. I would like to test and see if we cannot resolve this issue with the script.

**Comment by MattAttack07** [comment]
Changed the script to work for larger files, I tested this on a course that was just under 4GB (3.8GB) and I did not get any errors. Can you test the new script?

PR: https://github.com/unsupported/canvas/pull/46
