### ISSUE TITLE
bulk_upload_avatars.py IndexError: list index out of range

### ISSUE THREAD

**Issue by etsoft2k** [unsupported/canvas#28]
I get the following error when running bulk_upoad_avatars.py

'Done prepping Canvas for upload, now sending the data...'
Traceback (most recent call last):
  File "upload_avatars.py.", line 89, in <module>
    _data[1] = ('upload_params',_data[1][1].items())
IndexError: list index out of range

The csv file contain the headers and references to 2 images for 2 different sis_ids. 

Any ideas?

**Comment by bailegre** [comment]
I'm encountering the same error.  Did you resolve this issue?  Thanks.

**Comment by mrendon** [comment]
The way it's written it's expecting the canvas id, not the sis id. I was able to get it to work by changing it to pass the sis_user_id. For example
'as_user_id':'{0}'.format(user_image['user_id']) becomes
'as_user_id':'sis_user_id:{0}'.format(user_image['user_id'])
note sis_user_id:'

**Comment by bailegre** [comment]
Thanks!  Very helpful.

Greg
