### ISSUE TITLE
bulk_upload_avatars.py AttributeError: 'unicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by helm1980** [unsupported/canvas#53]
Traceback (most recent call last):
  File "F:\PROFILE\avatar-7.py", line 113, in <module>
    if ao.get('display_name')==user_image['image_filename']:
AttributeError: 'unicode' object has no attribute 'get'

**Comment by jbdammeier** [comment]
I'm having the same issue. Any luck fixing this?

**Comment by jbdammeier** [comment]
So I know WHY the error is getting generated. I inserted a print command to print avatar_options. It cam back as <Response [401]>. SO something with the initial get call is not working. I just don't yet know what that is.

**Comment by colincromar** [comment]
Currently the Canvas API only supports avatars that have hostnames matching *.instructure.com and *.gravatar.com. You can view the portion of code in Canvas that handles this [here](https://bit.ly/2w7JuF6).
